//
//  SearchResultsViewController.swift
//  iTunesAssignment
//
//  Created Mohamed anwar on 3/11/20.
//  Copyright © 2020 S4M. All rights reserved.
//
//  Template generated by @thetay
//

import UIKit

// MARK: View
class SearchResultsViewController: UIViewController {
    
    // MARK: IBOutlets
    @IBOutlet private weak var searchResultsCollectionView: UICollectionView!
    
    // MARK: Properties
    var output: SearchResultsViewControllerOutputProtocol!
    var router: SearchResultsRouter!
    var viewModel: SearchResultsModel.ViewModel?
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        fetchDataOnLoad()
        setupView()
    }
    
    // MARK: Fetch SearchResults
    private func fetchDataOnLoad() {
        // NOTE: Ask the Interactor to do some work
        
    }
    
    // MARK: SetupUI
    private func setupView() {
        setupCollectionView()
    }
    
    private func setupCollectionView() {
        searchResultsCollectionView.dataSource =  self
        searchResultsCollectionView.delegate =  self
    }
}

// MARK: UICollectionViewDataSource, UICollectionViewDelegate
extension SearchResultsViewController: UICollectionViewDataSource, UICollectionViewDelegate {
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        return UICollectionViewCell()
    }
    
}

// MARK: Connect View, Interactor, and Presenter
extension SearchResultsViewController: SearchResultsPresenterOutputProtocol {
    
}
