//
//  SearchResultsViewModel.swift
//  iTunesAssignment
//
//  Created Mohamed anwar on 3/11/20.
//  Copyright © 2020 S4M. All rights reserved.
//
//  Template generated by @thetay
//

struct SearchResultsModel {
    struct Request {
        
    }
    
    struct Response {
        
    }
    
    struct ViewModel {
        
    }
}
