//
//  SearchResultsConfigurator.swift
//  iTunesAssignment
//
//  Created Mohamed anwar on 3/11/20.
//  Copyright © 2020 S4M. All rights reserved.
//
//  Template generated by @thetay
//

import UIKit

class SearchResultsConfigurator {
    
    // MARK: Configuration
    class func viewcontroller() -> SearchResultsViewController {
        let viewController = SearchResultsViewController(nibName: "SearchResultsViewController", bundle: nil)
        
        let presenter = SearchResultsPresenter()
        presenter.output = viewController
        
        let interactor = SearchResultsInteractor()
        interactor.output = presenter
        
        let router = SearchResultsRouter()
        router.viewController = viewController

        viewController.output = interactor
        viewController.router = router
        
        return viewController
    }
}

// MARK: View Interface
protocol SearchResultsViewControllerOutputProtocol {

}

// MARK: Interactor Interface
protocol SearchResultsInteractorOutputProtocol {

}

// MARK: Presenter Interface
protocol SearchResultsPresenterOutputProtocol: class {
    
}

// MARK: Router
protocol SearchResultsRouterProtocol {

}
