//
//  SearchResultsWorker.swift
//  iTunesAssignment
//
//  Created Mohamed anwar on 3/11/20.
//  Copyright © 2020 S4M. All rights reserved.
//
//  Template generated by @thetay
//

class SearchResultsWorker {
    // MARK: Business Logic
    
    func doSomeWork() {
        // NOTE: Do the work
    }
}
